// Generated by CoffeeScript 1.11.1
var ach, transforms;

transforms = require('./transforms');

module.exports = ach = function(mainOptions) {
  return {
    hasParser: function(format) {
      return transforms.hasParser(format);
    },
    hasFormatter: function(format) {
      return transforms.hasFormatter(format);
    },
    getParser: function(format) {
      return transforms.getParser(format);
    },
    getFormatter: function(format) {
      return transforms.getFormatter(format);
    },
    from: require('./api/from'),
    create: require('./api/create'),
    wrap: require('./api/create/wrap')
  };
};
