// Generated by CoffeeScript 1.11.1
var JsonParser,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

module.exports = JsonParser = (function(superClass) {
  extend(JsonParser, superClass);

  function JsonParser() {
    JsonParser.__super__.constructor.call(this, {
      objectMode: true
    });
  }

  JsonParser.prototype._transform = function(data, encoding, done) {
    return done(null, JSON.parse(data));
  };

  return JsonParser;

})(require('stream').Transform);
