// Generated by CoffeeScript 1.11.1
var validate;

validate = require('../validate');

module.exports = function(index) {
  var batch, credit, debit, module, next, ref;
  batch = this.object.batches[index];
  if (batch == null) {
    return;
  }
  module = (function() {
    switch (batch.entryClassCode) {
      case 'CCD':
      case 'PPD':
        return './entry-ccd-ppd';
      case 'CTX':
        return './entry-ctx';
    }
  })();
  ref = require(module), credit = ref.credit, debit = ref.debit;
  next = {
    credit: credit,
    debit: debit,
    data: this.data,
    object: this.object,
    validate: validate.bind(this, this.object)
  };
  return next;
};
